name: dispatch-when-update-master-branch
on:
  push:
    branches:
      - master
      - feature/commit-hash
      - feature/pacakge-registry
permissions: write-all
jobs:
  release:
    name: dispatch Update-frontend-component workflow on frontend repo
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'
      - name: install
        run: npm install
      # まだpublishされていないバージョンならpublishする
      - name: publish
        run: |
          npx can-npm-publish --verbose && npm publish || echo "Does not publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # まだtagがないバージョンなら、Git Tagをpushする
      - name: package-version-to-git-tag
        uses: pkgdeps/action-package-version-to-git-tag@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"
      - name: use token
        run: echo "$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      - name: Repository dispatch
        run: |
          curl -H "Authorization: token ${{ steps.generate_token.outputs.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -X POST https://api.github.com/repos/operation-check-for-GHorganization/frontend/dispatches \
          -d '{"event_type":"update-frontend-component"}'
