name: dispatch-when-update-master-branch
on:
  push:
    branches:
      - master
      - feature/commit-hash
permissions: write-all
jobs:
  release:
    name: dispatch Update-frontend-component workflow on frontend repo
    runs-on: ubuntu-latest
    steps:
      - name: Repository dispatch
        run: |
          curl -X POST https://api.github.com/repos/operation-check-for-GHorganization/frontend/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -u ${{ secrets.APP_TOKEN }} \
          -d '{"event_type":"update-frontend-component"}'
