name: dispatch-when-update-master-branch
on:
  push:
    branches:
      - master
      - feature/commit-hash
jobs:
  release:
    name: dispatch Update-frontend-component workflow on frontend repo
    runs-on: ubuntu-latest
    steps:
      - name: Show github properties
        run: |
          echo ${{ github.workflow }}
          echo ${{ github.ref }}
          echo ${{ github.sha }}
      - name: Set var of request header
        run: |
          echo ::set-env name=REQUEST_HEADER::"'"Accept:application/vnd.github.everest-preview+json"'"

      - name: Set var of request body
        run: |
          echo ::set-env name=REQUEST_BODY::'{"event_type": "release", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "latesCommitSHA": ${{ github.sha }} }}'

      - name: Repository dispatch
        run: |
          curl -X POST https://api.github.com/repos/operation-check-for-GHorganization/frontend/dispatches \
          -H $REQUEST_HEADER \
          -u ${{ secrets.REPO_ACCESS_TOKEN }} \
          --data "$REQUEST_BODY"
